'use client';
import {useState} from 'react';
import {Folder,FileText,ArrowUpRight,Download,Code2,BookOpen} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import files from '@/lib/brain-files.json';
import {REPO_URL,COURSE_URL} from '@/lib/model';
export function SourceFile({path,label}:{path:string;label?:string}){const[open,setOpen]=useState(false);const content=(files as Record<string,string>)[path];return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger className="file-button"><FileText size={18}/><span>{label||path.split('/').pop()}</span><ArrowUpRight size={16}/></DialogTrigger><DialogContent className="source-dialog"><DialogTitle>{path}</DialogTitle><DialogDescription>The actual public source used for this session. You can read and adapt it.</DialogDescription><pre tabIndex={0}>{content||'This source is available in the GitHub repository.'}</pre><a className="button" href={`${REPO_URL}/blob/main/${path}`} target="_blank" rel="noreferrer">Open on GitHub <ArrowUpRight size={17}/></a></DialogContent></Dialog>}
export function Provenance(){return <div className="provenance"><div><span className="eyebrow">01 / THE KNOWLEDGE</span><h3>The second brain</h3><SourceFile path="second-brain/01-session/brief.md" label="The real session brief"/><SourceFile path="second-brain/02-method/knowledge-to-capability.md" label="The teaching method"/></div><div><span className="eyebrow">02 / THE INSTRUCTIONS</span><h3>The reusable skills</h3><SourceFile path="skills/build-web-presentation/SKILL.md" label="Build this presentation"/><SourceFile path="skills/build-audience-app/SKILL.md" label="Build the audience app"/></div><div><span className="eyebrow">03 / THE RESULT</span><h3>You’re inside it</h3><a className="file-button" href={`${REPO_URL}/tree/main/app-source`} target="_blank" rel="noreferrer"><Code2 size={18}/>The working app source<ArrowUpRight size={16}/></a><a className="file-button" href={`${REPO_URL}/blob/main/BUILD-RECEIPT.md`} target="_blank" rel="noreferrer"><FileText size={18}/>The build & test receipt<ArrowUpRight size={16}/></a></div></div>}
export function Kit({compact=false}:{compact?:boolean}){return <section className={`kit ${compact?'compact':''}`}><div className="kit-intro"><p className="eyebrow">THE WORKSHOP BEHIND THE WORKSHOP</p><h2>Open it.<br/>Change it.<br/><em>Make it yours.</em></h2><p>The actual course second brain. Seven reusable skills. The source behind this presentation and app. A guide to get started.</p><div className="button-row"><a className="button primary" href={`${REPO_URL}/archive/refs/heads/main.zip`}><Download size={18}/>Download everything</a><a className="button" href={REPO_URL} target="_blank" rel="noreferrer">Explore on GitHub<ArrowUpRight size={17}/></a></div><p className="micro">No GitHub account needed to read or download.</p></div><div className="kit-tree"><div className="file-bar"><span>CAPABILITY-LAB /</span><span>YOURS TO KEEP</span></div><SourceFile path="START-HERE.md" label="START-HERE.md"/><div className="tree-folder"><Folder size={17}/><b>second-brain/</b><span>The knowledge behind the session</span></div><SourceFile path="second-brain/INDEX.md" label="INDEX.md"/><div className="tree-folder"><Folder size={17}/><b>skills/</b><span>The recipes behind every asset</span></div>{['build-learning-board','build-web-presentation','build-audience-app','build-learning-asset','build-take-home-kit','check-session','update-second-brain'].map(s=><SourceFile key={s} path={`skills/${s}/SKILL.md`} label={s}/>)}<div className="tree-folder"><Code2 size={17}/><b>app-source/</b><span>The working code and tests</span></div><a className="file-button" href="/guide"><BookOpen size={18}/>User manual<ArrowUpRight size={16}/></a></div></section>}
export function CourseLinks(){return <section className="course-links"><p className="eyebrow">KEEP EXPLORING</p><h2>The Second Brain Blueprint</h2><p>John’s four recorded sessions, with the original starter vault.</p><div className="resource-list">{[['1','Why build one','6zSG6SWA-Js'],['2','Your first vault','olvJH--I0T0'],['3','Reusable skills','WuP79sQ0O9s'],['4','Keep it alive','KXNJLduVeCc']].map(([n,t,id])=><a key={id} href={`https://www.youtube.com/watch?v=${id}`} target="_blank" rel="noreferrer"><span>PART {n}</span><h3>{t}</h3><ArrowUpRight size={22}/></a>)}</div><a className="text-link" href={COURSE_URL} target="_blank" rel="noreferrer">Open the free course hub<ArrowUpRight size={17}/></a></section>}
