'use client';
import {lazy,Suspense,useCallback,useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Download,Expand,PenLine,Check,RotateCcw,FileImage} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {SourceFile} from './kit';
import lesson from '@/lib/learning-board.json';
import {REPO_URL,SITE_URL} from '@/lib/model';
import type {CanvasActions} from './excalidraw-canvas';
const Canvas=lazy(()=>import('./excalidraw-canvas'));
const topics=lesson.topics;
export function LearningBoard({embedded=false,initialTopic=null,draft=false,standalone=false}:{embedded?:boolean;initialTopic?:string|null;draft?:boolean;standalone?:boolean}){
 const[ready,setReady]=useState(false),[topic,setTopic]=useState<string|null>(initialTopic),[editing,setEditing]=useState(false),[actions,setActions]=useState<CanvasActions|null>(null),[answer,setAnswer]=useState<string|null>(null),[checks,setChecks]=useState<string[]>([]),[note,setNote]=useState(''),[remaining,setRemaining]=useState(180),[running,setRunning]=useState(false);
 const receive=useCallback((a:CanvasActions)=>setActions(a),[]);
 useEffect(()=>{(window as unknown as {EXCALIDRAW_ASSET_PATH:string}).EXCALIDRAW_ASSET_PATH=standalone?'./excalidraw-assets/':'/excalidraw-assets/';setReady(true);if(!embedded){const hash=location.hash.slice(1);if(topics.some(t=>t.id===hash))setTopic(hash)}},[embedded,standalone]);
 useEffect(()=>{if(!running||remaining===0)return;const end=Date.now()+remaining*1000;const timer=setInterval(()=>setRemaining(Math.max(0,Math.ceil((end-Date.now())/1000))),250);return()=>clearInterval(timer)},[running,remaining]);
 const current=topics.find(t=>t.id===topic),index=topics.findIndex(t=>t.id===topic),choice=current?.choices?.find(c=>c.id===answer);
 function go(id:string|null){setTopic(id);if(!embedded)history.replaceState(null,'',location.pathname+(id?'#'+id:''))}
 function keepNote(){const content=`# My next one-to-one\n\n${note.trim()}\n\nRehearsal check: ${checks.length}/3 behaviours practised.\n\nAsk an open question. Listen before advising. Agree an action, owner and follow-up date.\n\nLearning example: ${SITE_URL}/board\n`;const url=URL.createObjectURL(new Blob([content],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='my-next-one-to-one.md';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className={`learning-board ${embedded?'embedded':''} ${standalone?'standalone':''}`} aria-label="Better first one-to-ones learning board">
 {!embedded&&<header className="board-top"><a className="board-brand" href={standalone?SITE_URL:'/'}>CAPABILITY LAB<span>LEARNING BOARD / 01</span></a><nav aria-label="Board resources"><a href={standalone?SITE_URL+'/brain':'/brain'}>The brain<ArrowUpRight size={16}/></a><a href={REPO_URL+'/blob/main/skills/build-learning-board/SKILL.md'} target="_blank" rel="noreferrer">The skill<ArrowUpRight size={16}/></a><a href={standalone?SITE_URL+'/resources':'/resources'}>Make your own<ArrowUpRight size={16}/></a><a href={standalone?SITE_URL+'/present':'/present'}>Present<ArrowUpRight size={16}/></a></nav></header>}
 <div className="board-titlebar"><div><p className="eyebrow">{draft?'FIRST DRAFT / JUST THE DEFINITIONS':'ASK · LISTEN · AGREE'}</p><h1>{lesson.title}</h1></div><span className="board-duration">10 MINUTES<span>One useful conversation</span></span></div>
 <div className="board-workspace"><div className="board-map-column"><div className="board-map"><Suspense fallback={<div className="board-loading">Opening your learning board…</div>}>{ready&&<Canvas topic={topic} onTopic={go} editing={editing} draft={draft} onReady={receive}/>}</Suspense><div className="map-hint">Drag to explore · Pinch or scroll to zoom</div></div><div className="board-toolbar"><button onClick={()=>go(null)} aria-pressed={!topic}><Expand size={17}/>Whole board</button><button onClick={()=>setEditing(!editing)} aria-pressed={editing}><PenLine size={17}/>{editing?'Finish editing':'Edit a copy'}</button><button disabled={!actions} onClick={()=>actions?.save()}><Download size={17}/>Save board</button><button disabled={!actions} onClick={()=>actions?.svg()} aria-label="Download board as SVG"><FileImage size={17}/><span className="optional-label">SVG</span></button></div>{editing&&<p className="edit-notice">Editing your local copy. Save board to keep your changes before leaving.</p>}<nav className="board-stops" aria-label="Learning stops">{topics.map(t=><button key={t.id} onClick={()=>go(t.id)} aria-pressed={topic===t.id}><span>{t.number}</span>{t.short}</button>)}</nav></div>
 <aside className="learning-panel" aria-live="polite">{current?<><div className="panel-step"><span>STOP {current.number} / 06</span><span>{current.minutes} MIN</span></div><h2>{current.headline}</h2><p className="learning-summary">{current.summary}</p>{current.id==='try'?<><div className="decision-options" role="group" aria-label="What would you say to Sam?">{current.choices?.map(c=><button key={c.id} onClick={()=>setAnswer(c.id)} aria-pressed={answer===c.id}><span>{c.id.toUpperCase()}</span>{c.text}</button>)}</div>{choice&&<div className={`decision-feedback ${choice.correct?'correct':''}`} role="status"><strong>{choice.correct?'A useful opening.':'Try a more open question.'}</strong><p>{choice.feedback}</p>{!choice.correct&&<button onClick={()=>setAnswer(null)}>Try again<RotateCcw size={15}/></button>}</div>}</>:<p className="learning-detail">{current.detail}</p>}
 {current.id==='practice'?<div className="practice-panel"><div className="practice-clock"><strong>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</strong><button onClick={()=>{if(remaining===0)setRemaining(180);setRunning(!running)}}>{remaining===0?'Restart':running?'Pause':'Start rehearsal'}</button><button aria-label="Reset rehearsal timer" onClick={()=>{setRunning(false);setRemaining(180)}}><RotateCcw size={16}/></button></div>{['Asked an open question','Reflected what I heard','Agreed an action, owner and date'].map(c=><label className="practice-check" key={c}><Checkbox checked={checks.includes(c)} onCheckedChange={v=>setChecks(v?[...checks,c]:checks.filter(x=>x!==c))}/>{c}</label>)}<label className="action-label">My next action<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={3000} placeholder="I will… by… and check back on…"/></label><button className="button primary" disabled={!note.trim()} onClick={keepNote}><Download size={17}/>Keep my action</button><small>Stays in this tab. Download it before leaving.</small></div>:<blockquote>{current.prompt}</blockquote>}
 <SourceFile path={current.source} label="Read the source behind this stop"/><div className="learning-next"><button onClick={()=>go(index>0?topics[index-1].id:null)}><ArrowLeft size={17}/>{index>0?'Previous':'Overview'}</button>{index<topics.length-1?<button onClick={()=>go(topics[index+1].id)}>Next stop<ArrowRight size={17}/></button>:<button onClick={()=>go(null)}>Whole board<Expand size={17}/></button>}</div></>:<><div className="panel-step"><span>YOUR TEN-MINUTE PATH</span><Check size={18}/></div><h2>A better conversation starts here.</h2><p className="learning-summary">{lesson.outcome}</p><p className="learning-detail">Follow the six stops, try Sam’s situation, then rehearse it with a colleague. Click through at your own pace.</p><button className="button primary start-board" onClick={()=>go('start')}>Start the walkthrough<ArrowRight size={20}/></button><ol className="board-itinerary">{topics.map(t=><li key={t.id}><button onClick={()=>go(t.id)}><span>{t.number}</span>{t.title}<small>{t.minutes}m</small></button></li>)}</ol><p className="board-source-note">{lesson.fictional}. An illustrative framework; use your organisation’s guidance for real situations.</p></>}</aside></div>
 </section>
}
