'use client';
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Download,Play,Plus,Check} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {LearningBoard} from './learning-board';
import {BrainBrowser} from './brain-browser';
import {SourceFile,Provenance} from './kit';
import {TakeawayLinks,SimpleLaunch} from './takeaway-links';
import {REPO_URL,SITE_URL} from '@/lib/model';
import session from '@/lib/session.json';

export function OpenBoard({label='Explore the live board',image=true,topic=null}:{label?:string;image?:boolean;topic?:string|null}){return <Dialog><DialogTrigger className={image?'board-picture':'button primary'}>{image?<><img src="/board-preview.svg" alt="The complete Excalidraw learning board: Start, Ask, Listen, Agree, Meet Sam, Make it yours"/><span><Play size={22}/>{label}<ArrowUpRight size={20}/></span></>:<>{label}<ArrowUpRight size={20}/></>}</DialogTrigger><DialogContent className="board-dialog"><DialogTitle className="sr-only">Better first one-to-ones interactive board</DialogTitle><DialogDescription className="sr-only">Follow the learning stops, pan and zoom the diagram, then try the scenario and practice activity.</DialogDescription><LearningBoard embedded initialTopic={topic}/></DialogContent></Dialog>}
function Pattern(){return <div className="pattern-triptych"><div><span>01 / THE BRAIN</span><h3>What to teach.</h3><p>The learner.<br/>The knowledge.<br/>The outcome.</p><SourceFile path="learning-brain/00-brief.md" label="Open the actual brain"/></div><b>+</b><div><span>02 / THE SKILL</span><h3>How to build it.</h3><p>The instructions.<br/>The interactions.<br/>The quality bar.</p><SourceFile path="skills/build-learning-board/SKILL.md" label="Open the actual skill"/></div><b>→</b><div><span>03 / THE OUTPUT</span><h3>Something to use.</h3><p>An interactive board.<br/>A decision to try.<br/>A learning asset to keep.</p><OpenBoard image={false} label="Open the actual output"/></div></div>}
function BuildRecipe(){const[step,setStep]=useState(0);const steps=[['Read the brain','What should this learner be able to do?'],['Design the journey','Orient. Understand. Decide. Rehearse. Apply.'],['Build the board','Editable Excalidraw + a web experience.'],['Refine the learning','Use the outcome and quality bar to improve it.'],['Check & launch','Test it, review it, then give people the link.']];return <div className="recipe-stage"><div className="recipe-steps">{steps.map(([title],i)=><button key={title} onClick={()=>setStep(i)} aria-pressed={step===i}><span>0{i+1}</span>{title}</button>)}</div><div className="recipe-explanation"><p>{steps[step][1]}</p><SourceFile path="skills/build-learning-board/SKILL.md" label="Read the full SKILL.md"/></div></div>}
function Refine(){const[refined,setRefined]=useState(false);return <div className="refinement"><div className="refinement-controls"><button onClick={()=>setRefined(false)} aria-pressed={!refined}>1. The first draft</button><ArrowRight/><button onClick={()=>setRefined(true)} aria-pressed={refined}>2. The useful refinement</button></div><div className="refinement-content"><div><p className="eyebrow">{refined?'NOW THERE IS SOMETHING TO PRACTISE':'THREE DEFINITIONS ARE ONLY A START'}</p><h3>{refined?'“What would you say to Sam?”':'Ask. Listen. Agree.'}</h3><p>{refined?'A real decision. A reason for each answer. A rehearsal. One next action.':'A learner can read the framework. But have they practised the conversation?'}</p><div className="button-row">{refined?<OpenBoard image={false} topic="try" label="Try the refined experience"/>:<button className="button primary" onClick={()=>setRefined(true)}>Add a decision & practice<Plus size={20}/></button>}<SourceFile path="learning-brain/05-refinements.md" label="See the refinement note"/></div></div><div className="refinement-visual">{refined?<img src="/board-preview.svg" alt="Refined six-stop board with decision and practice"/>:<div className="draft-definitions">{[['Ask','One open question.'],['Listen','Reflect what you hear.'],['Agree','Decide the next step.']].map(([a,b])=><div key={a}><h4>{a}</h4><p>{b}</p></div>)}</div>}<span>{refined?'CURRENT OUTPUT / LEARNING THROUGH DOING':'FIRST DRAFT / READING THE DEFINITIONS'}</span></div></div></div>}
function YourBrain(){const[values,setValues]=useState({topic:'A useful first one-to-one',audience:'Newly promoted managers',outcome:'Ask, listen and agree one clear next step',sources:'The approved framework and realistic examples'});const[step,setStep]=useState(0);const fields=[['topic','What do you want to teach?'],['audience','Who is it for?'],['outcome','What should they be able to do?'],['sources','What should the brain know?']] as const;const[key,label]=fields[step];return <div className="your-brain"><div>{fields.map(([k,l],i)=><button key={k} onClick={()=>setStep(i)} aria-pressed={step===i}><span>0{i+1}</span>{l}</button>)}</div><div className="brain-answer"><label>{label}<textarea aria-label={label} value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})} maxLength={2000}/></label>{step<3?<button className="button primary" onClick={()=>setStep(step+1)}>Next ingredient<ArrowRight size={20}/></button>:<a className="button primary" href={REPO_URL+'/archive/refs/heads/main.zip'}><Download size={20}/>Take the starter brain</a>}<p>One topic. One audience. One useful behaviour.</p></div></div>}
export function TeachingScene({index}:{index:number}){const s=session.frames[index];return <div className={'scene story-scene story-'+s.visual}><div className="scene-title"><p className="eyebrow">{s.eyebrow}</p><h1>{s.title}<br/><em>{s.accent}</em></h1>{s.visual!=='hero'&&<p className="scene-subtitle">{s.body}</p>}</div>
 {s.visual==='hero'&&<><img className="stage-art" src="/brand/capability-loop.png" alt=""/><div className="stage-byline"><span>John Gordon</span><span>Chief Product Officer · Mediazoo Group</span><small>PERITUS LEARNING / 30 MINUTES</small></div></>}
 {s.visual==='intro'&&<><img className="speaker-portrait" src="/brand/john-gordon.png" alt="John Gordon"/><div className="speaker-bio"><p>Chief Product Officer<br/>Mediazoo Group</p><span>Product, AI and practical learning.<br/>Building with Finer Vision.</span><a href="https://www.mediazoo.tv/news-and-views/mediazoo-group-appoints-chief-product-officer-to-lead-ai-growth" target="_blank" rel="noreferrer">My story<ArrowUpRight size={18}/></a></div></>}
 {s.visual==='board'&&<div className="stage-board-layout"><OpenBoard/><aside><p>A first one-to-one.<br/>For a new manager.</p><span>Explore → Decide → Practise</span><a className="button" href={SITE_URL+'/board'} target="_blank" rel="noreferrer">Open in its own tab<ArrowUpRight size={18}/></a></aside></div>}
 {s.visual==='pattern'&&<Pattern/>}
 {s.visual==='brain'&&<BrainBrowser compact/>}
 {s.visual==='skill'&&<BuildRecipe/>}
 {s.visual==='output'&&<div className="output-story"><div className="build-prompt"><span>THE BUILD INSTRUCTION</span><p>“Read the learning brain.<br/>Use the build-learning-board skill.<br/>Create the interactive learning board.”</p><SourceFile path="skills/build-learning-board/SKILL.md" label="The saved instruction"/></div><OpenBoard label="Inspect the working output"/></div>}
 {s.visual==='refine'&&<Refine/>}
 {s.visual==='launch'&&<div className="launch-story"><div><p>The board is ready.<br/>The next step is a learner.</p><ul><li><Check/>Open it on a phone.</li><li><Check/>Try the decision and feedback.</li><li><Check/>Run the rehearsal with a colleague.</li></ul><OpenBoard image={false}/></div><a className="single-qr" href={SITE_URL+'/board'} target="_blank" rel="noreferrer"><img src="/qr-board.svg" alt="Scan to open the learning board"/><strong>Try the board now<ArrowUpRight size={22}/></strong><span>/board · No sign-up</span></a></div>}
 {s.visual==='yourbrain'&&<YourBrain/>}
 {s.visual==='impact'&&<div className="impact-scene">{[['Engagement','A decision to make.','People practise a conversation they actually face.'],['Visibility','A source you can show.','The brief, skill and quality checks are inspectable.'],['Impact','A behaviour to observe.','Can the manager ask, listen and agree a next step?']].map(([a,b,c])=><div key={a}><span>{a}</span><h3>{b}</h3><p>{c}</p></div>)}</div>}
 {s.visual==='reveal'&&<Provenance/>}
 {s.visual==='takeaways'&&<TakeawayLinks/>}
 {s.visual==='download'&&<SimpleLaunch/>}
 {s.visual==='reuse'&&<div className="reuse-story"><div className="reuse-path"><span>Create your brain</span><ArrowRight/><span>Use the skill</span><ArrowRight/><span>Build & refine</span><ArrowRight/><span>Launch</span></div><blockquote>“Help me adapt this learning board to teach <em>[my topic]</em> to <em>[my audience]</em>. Read the brain and skill. Build it, show me, refine it from my feedback, and prepare the launch folder.”</blockquote><p>Open the downloaded folder in an AI coding tool with file access, such as Codex or Claude Code. Start with <b>START-HERE.md</b>.</p></div>}
 {s.visual==='close'&&<div className="close-story"><p>Create a brain for something<br/>you want to teach.</p><div><span>The skill is yours.</span><span>The board is yours.</span><span>The pattern is yours.</span></div><a className="button primary" href={REPO_URL} target="_blank" rel="noreferrer">Take it from here<ArrowUpRight size={21}/></a></div>}
 </div>}
