import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFile} from 'node:fs/promises';
test('canvas clicks open a stop and edits survive in the exported board',async({page,isMobile})=>{
 test.skip(isMobile,'Editing workstation workflow');await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:1440,height:1000});await page.goto('/board');await page.locator('[data-canvas-ready=true]').waitFor();await expect(page.getByRole('button',{name:'Reset zoom'})).not.toHaveText('100%');const box=(await page.locator('.board-map').boundingBox())!;await page.locator('.board-map').click({position:{x:box.width*.2,y:box.height*.38}});await expect(page.getByRole('heading',{name:'You do not need all the answers.'})).toBeVisible();await page.getByRole('button',{name:'Edit a copy'}).click();await page.locator('label').filter({has:page.getByRole('radio',{name:'Rectangle',exact:true})}).click();await expect(page.getByRole('radio',{name:'Rectangle',exact:true})).toBeChecked();await page.mouse.move(box.x+box.width*.35,box.y+box.height*.3);await page.mouse.down();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.45,{steps:8});await page.mouse.up();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save board',exact:true}).click();const data=JSON.parse(await readFile((await(await download).path())!,'utf8'));expect(data.elements.filter((e:{type:string})=>e.type==='rectangle').length).toBeGreaterThan(6);
});
test('the real board opens, zooms through a lesson and returns to the overview',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/board');await page.locator('[data-canvas-ready=true]').waitFor();await page.getByRole('button',{name:'Start the walkthrough'}).click();await expect(page.getByRole('heading',{name:'You do not need all the answers.'})).toBeVisible();for(const heading of ['Open the conversation.','Understand before you solve.','Make the next step clear.','What would you say next?','Three minutes. One better conversation.']){await page.getByRole('button',{name:'Next stop',exact:true}).click();await expect(page.getByRole('heading',{name:heading})).toBeVisible()}await page.getByRole('button',{name:'Whole board',exact:true}).first().click();await expect(page.getByRole('heading',{name:'A better conversation starts here.'})).toBeVisible();expect(errors).toEqual([]);
});
test('a learner gets meaningful feedback, can retry, rehearse and keep an action',async({page})=>{
 await page.goto('/board#try');await page.getByRole('button',{name:/A Try making/}).click();await expect(page.getByRole('status')).toContainText('Advice arrives before');await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('button',{name:/B Which change/}).click();await expect(page.getByRole('status')).toContainText('without assuming the cause');await page.getByRole('button',{name:'Next stop',exact:true}).click();await page.getByRole('button',{name:'Start rehearsal'}).click();await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeVisible();await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByRole('checkbox',{name:'Asked an open question'}).check();await page.getByLabel('My next action').fill('I will ask Sam what changed, then agree a follow-up on Friday.');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Keep my action'}).click();const text=await readFile((await(await download).path())!,'utf8');expect(text).toContain('follow-up on Friday');expect(text).toContain('1/3 behaviours');
});
test('the output downloads as editable Excalidraw and SVG',async({page})=>{
 await page.goto('/board');await page.getByRole('button',{name:'Save board',exact:true}).waitFor();await expect(page.getByRole('button',{name:'Save board',exact:true})).toBeEnabled();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save board',exact:true}).click();const board=JSON.parse(await readFile((await(await download).path())!,'utf8'));expect(board.type).toBe('excalidraw');expect(board.elements.length).toBeGreaterThan(30);expect(board.elements.filter((e:{type:string})=>e.type==='rectangle')).toHaveLength(6);const svgDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download board as SVG'}).click();expect(await readFile((await(await svgDownload).path())!,'utf8')).toContain('<svg');await page.getByRole('button',{name:'Edit a copy'}).click();await expect(page.getByText('Editing your local copy.')).toBeVisible();await page.getByRole('button',{name:'Finish editing'}).click();
});
test('brain and skill are the real source files and link to exact GitHub paths',async({page})=>{
 await page.goto('/brain');await expect(page.locator('.brain-prose')).toContainText('Teach: a useful first one-to-one');await page.getByRole('button',{name:'02-framework'}).click();await expect(page.locator('.brain-prose')).toContainText('Ask, Listen, Agree');await expect(page.getByRole('link',{name:'Open selected file on GitHub'})).toHaveAttribute('href',/learning-brain\/02-framework.md$/);await page.getByRole('tab',{name:'This session’s brain'}).click();await expect(page.locator('.brain-prose')).toContainText('Speaker: John Gordon');await page.goto('/present#recipe');await page.getByRole('button',{name:'Read the full SKILL.md'}).click();await expect(page.getByRole('dialog').locator('pre')).toContainText('Build a learning board');
});
test('clicking the picture opens the working board and returns to the same scene',async({page})=>{
 await page.goto('/present#board');await page.getByRole('button',{name:'Explore the live board'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('[data-canvas-ready=true]').waitFor();await page.getByRole('button',{name:'Try a decision'}).first().click();await expect(page.getByRole('heading',{name:'What would you say next?'})).toBeVisible();await page.getByRole('button',{name:/B Which change/}).click();await expect(page.getByRole('status')).toContainText('without assuming');await page.getByRole('button',{name:'Close',exact:true}).last().click();await expect(page.locator('.scene-title h1')).toContainText('A board you can');await expect(page).toHaveURL(/#board$/);
});
test('three distinct QRs have the corresponding clickable destinations',async({page})=>{
 await page.goto('/present#kit');const links=page.locator('.takeaway-qrs>a');await expect(links).toHaveCount(3);await expect(links.nth(0)).toHaveAttribute('href',/\/board$/);await expect(links.nth(1)).toHaveAttribute('href',/\/brain$/);await expect(links.nth(2)).toHaveAttribute('href','https://github.com/MediazooGroup/capability-lab');for(const img of await links.locator('img').all())expect(await img.evaluate(e=>(e as HTMLImageElement).complete&&(e as HTMLImageElement).naturalWidth>0)).toBe(true);await page.goto('/resources');await expect(page.getByText('Download. Unzip.',{exact:true})).toBeVisible();await expect(page.getByText('Put it live.',{exact:true})).toBeVisible();
});
for(const route of ['/board','/board#try','/board#practice','/brain'])test(`accessible learning experience: ${route}`,async({page})=>{
 await page.goto(route);await page.locator('#main[data-ready=true]').waitFor();if(route.startsWith('/board'))await page.locator('[data-canvas-ready=true]').waitFor();const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);
});
