import {test,expect} from '@playwright/test';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
test('the launch-ready board works directly from a file with no network',async({page,context},info)=>{
 test.skip(info.project.name!=='desktop-chromium','Desktop download workflow');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await context.setOffline(true);await page.goto(pathToFileURL(path.resolve('launch-ready/index.html')).href);await page.locator('[data-canvas-ready=true]').waitFor();await page.getByRole('button',{name:'Try a decision'}).first().click();await page.getByRole('button',{name:/B Which change/}).click();await expect(page.getByRole('status')).toContainText('without assuming');await page.getByRole('button',{name:'Read the source behind this stop'}).click();await expect(page.getByRole('dialog').locator('pre')).toContainText('Sam says:');expect(errors).toEqual([]);
});
test('offline presentation has the portrait, board picture, three QRs and real board',async({page,context},info)=>{
 test.skip(info.project.name!=='desktop-chromium','Desktop presenter backup');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await context.setOffline(true);await page.goto(pathToFileURL(path.resolve('public/offline-presentation.html')).href+'#me');await expect(page.locator('.speaker-portrait')).toBeVisible();expect(await page.locator('.speaker-portrait').evaluate(e=>(e as HTMLImageElement).naturalWidth)).toBeGreaterThan(1000);await page.getByRole('button',{name:'Next scene',exact:true}).click();expect(await page.locator('.board-picture img').evaluate(e=>(e as HTMLImageElement).naturalWidth)).toBeGreaterThan(500);await page.getByRole('button',{name:'Explore the live board'}).click();await page.locator('[data-canvas-ready=true]').waitFor();await page.getByRole('button',{name:'Start the walkthrough'}).click();await expect(page.getByRole('heading',{name:'You do not need all the answers.'})).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).last().click();await page.keyboard.press('o');await page.getByRole('button',{name:/Try it. Read it./}).click();for(const img of await page.locator('.takeaway-qrs img').all())expect(await img.evaluate(e=>(e as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);expect(errors).toEqual([]);
});
